# Site settings
title: Tot al punt
description: "Comida casera para llevar"
baseurl: ""
url: "http://totalpunt.es/"
tap:
  twitter: "https://twitter.com/totalpunt"
  instagram: "https://www.instagram.com/rostisseria_tot_al_punt/"
  facebook: "https://www.facebook.com/totalpunt/"

# Build settings
markdown: kramdown
permalink: pretty
exclude:
    - node_modules
